=== tsilvs/bash_utils/data/linux_conf/path-map.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "array",
	"items": {
		"type": "object",
		"properties": {
			"order": {
				"type": "string",
				"pattern": "^\\d+\\.\\d+$",
				"description": "Hierarchical order like '0.0'"
			},
			"title": {
				"type": "string",
				"description": "Descriptive title of the config group"
			},
			"keywords": {
				"type": "array",
				"items": {
					"type": "string"
				},
				"description": "Keywords extracted from title for search/filtering"
			},
			"paths": {
				"type": "object",
				"properties": {
					"system": {
						"type": "array",
						"items": {
							"type": "string",
							"pattern": "TBD???"
						},
						"description": "System-wide config paths"
					},
					"user": {
						"type": "array",
						"items": {
							"type": "string",
							"pattern": "TBD???"
						},
						"description": "User home config paths (relative to ~)"
					}
				},
				"required": ["system", "user"],
				"additionalProperties": false
			}
		},
		"required": ["order", "title", "keywords", "paths"],
		"additionalProperties": false
	}
}

=== tsilvs/bash_utils/data/linux_conf/path-map.json
[
	{
		"order": "0.0",
		"title": "Bootloader: Grub",
		"keywords": [
			"Bootloader",
			"Grub"
		],
		"paths": {
			"system": [
				"/boot/grub2/user.cfg",
				"/etc/default/grub",
				"/boot/grub2/grubenv"
			],
			"user": []
		}
	},
	{
		"order": "0.1",
		"title": "Early Boot / initramfs",
		"keywords": [
			"Early Boot",
			"initramfs",
			"RHEL",
			"Fedora",
			"Debian",
			"Ubuntu"
		],
		"paths": {
			"system": [
				"/etc/dracut.conf.d/",
				"/etc/initramfs-tools/"
			],
			"user": []
		}
	},
	{
		"order": "0.2",
		"title": "Early Boot / Encryption",
		"keywords": [
			"Early Boot",
			"Encryption"
		],
		"paths": {
			"system": [
				"/etc/crypttab"
			],
			"user": []
		}
	},
	{
		"order": "0.3",
		"title": "Early Boot / Mount",
		"keywords": [
			"Early Boot",
			"Mount"
		],
		"paths": {
			"system": [
				"/etc/fstab"
			],
			"user": []
		}
	},
	{
		"order": "1.0",
		"title": "Kernel / Modules",
		"keywords": [
			"Kernel",
			"Modules"
		],
		"paths": {
			"system": [
				"/etc/modprobe.d/",
				"/etc/modules-load.d/"
			],
			"user": []
		}
	},
	{
		"order": "1.1",
		"title": "Kernel / sysctl",
		"keywords": [
			"Kernel",
			"sysctl"
		],
		"paths": {
			"system": [
				"/etc/sysctl.d/"
			],
			"user": []
		}
	},
	{
		"order": "1.2",
		"title": "Kernel / Runtime",
		"keywords": [
			"Kernel",
			"Runtime"
		],
		"paths": {
			"system": [
				"/etc/kernel/"
			],
			"user": []
		}
	},
	{
		"order": "1.3",
		"title": "Kernel / Binary Formats",
		"keywords": [
			"Kernel",
			"Binary Formats"
		],
		"paths": {
			"system": [
				"/etc/binfmt.d/"
			],
			"user": []
		}
	},
	{
		"order": "1.4",
		"title": "Kernel / Modules Load",
		"keywords": [
			"Kernel",
			"Modules Load"
		],
		"paths": {
			"system": [
				"/etc/depmod.d/"
			],
			"user": []
		}
	},
	{
		"order": "2.0",
		"title": "Device Management / udev",
		"keywords": [
			"Device Management",
			"udev"
		],
		"paths": {
			"system": [
				"/etc/udev/rules.d/"
			],
			"user": []
		}
	},
	{
		"order": "2.1",
		"title": "Device Management / LVM",
		"keywords": [
			"Device Management",
			"LVM"
		],
		"paths": {
			"system": [
				"/etc/lvm/"
			],
			"user": []
		}
	},
	{
		"order": "2.2",
		"title": "File Systems / ZFS",
		"keywords": [
			"File Systems",
			"ZFS"
		],
		"paths": {
			"system": [
				"/etc/zfs-fuse/"
			],
			"user": []
		}
	},
	{
		"order": "2.3",
		"title": "File Systems / FUSE",
		"keywords": [
			"File Systems",
			"FUSE"
		],
		"paths": {
			"system": [
				"/etc/fuse.conf"
			],
			"user": []
		}
	},
	{
		"order": "2.4",
		"title": "File Systems / Btrfs",
		"keywords": [
			"File Systems",
			"Btrfs"
		],
		"paths": {
			"system": [
				"/etc/btrfs-assistant.conf"
			],
			"user": []
		}
	},
	{
		"order": "3.0",
		"title": "Init / SysV",
		"keywords": [
			"Init",
			"SysV"
		],
		"paths": {
			"system": [
				"/etc/init.d/"
			],
			"user": []
		}
	},
	{
		"order": "3.0",
		"title": "Init / SysV compat",
		"keywords": [
			"Init",
			"SysV compat"
		],
		"paths": {
			"system": [
				"/etc/rc.local"
			],
			"user": []
		}
	},
	{
		"order": "3.1",
		"title": "Init / systemd",
		"keywords": [
			"Init",
			"systemd"
		],
		"paths": {
			"system": [
				"/etc/systemd/system/",
				"/usr/lib/systemd/system/"
			],
			"user": [
				"~/.config/systemd/user/",
				"~/.local/share/systemd/user/"
			]
		}
	},
	{
		"order": "3.2",
		"title": "Scheduled Tasks",
		"keywords": [
			"Scheduled Tasks"
		],
		"paths": {
			"system": [
				"/etc/cron.d/",
				"/etc/systemd/system/timers.target.wants/"
			],
			"user": [
				"~/.config/systemd/user/timers/"
			]
		}
	},
	{
		"order": "3.3",
		"title": "Scheduled Tasks / Cron",
		"keywords": [
			"Scheduled Tasks",
			"Cron"
		],
		"paths": {
			"system": [
				"/etc/cron.d/",
				"/etc/crontab",
				"/etc/cron.daily/",
				"/etc/cron.hourly/",
				"/etc/cron.weekly/",
				"/etc/cron.monthly/"
			],
			"user": []
		}
	},
	{
		"order": "4.0",
		"title": "Network / Core",
		"keywords": [
			"Network",
			"Core"
		],
		"paths": {
			"system": [
				"/etc/NetworkManager/",
				"/etc/netplan/",
				"/etc/systemd/network/",
				"/etc/hosts",
				"/etc/hostname",
				"/etc/resolv.conf",
				"/etc/services",
				"/etc/protocols",
				"/etc/networks",
				"/etc/ethertypes",
				"/etc/netconfig"
			],
			"user": []
		}
	},
	{
		"order": "4.1",
		"title": "Network / DNS",
		"keywords": [
			"Network",
			"DNS"
		],
		"paths": {
			"system": [
				"/etc/dnsmasq.conf",
				"/etc/dnsmasq.d/",
				"/etc/unbound/"
			],
			"user": []
		}
	},
	{
		"order": "4.1",
		"title": "Network / Zeroconf",
		"keywords": [
			"Network",
			"Zeroconf"
		],
		"paths": {
			"system": [
				"/etc/avahi/"
			],
			"user": []
		}
	},
	{
		"order": "4.2",
		"title": "Network / DHCP",
		"keywords": [
			"Network",
			"DHCP"
		],
		"paths": {
			"system": [
				"/etc/dhcp/"
			],
			"user": []
		}
	},
	{
		"order": "4.3",
		"title": "Network / NFS",
		"keywords": [
			"Network",
			"NFS"
		],
		"paths": {
			"system": [
				"/etc/nfs.conf",
				"/etc/nfsmount.conf",
				"/etc/exports",
				"/etc/exports.d/"
			],
			"user": []
		}
	},
	{
		"order": "4.4",
		"title": "Network / iSCSI",
		"keywords": [
			"Network",
			"iSCSI"
		],
		"paths": {
			"system": [
				"/etc/iscsi/"
			],
			"user": []
		}
	},
	{
		"order": "4.5",
		"title": "Network / VPN",
		"keywords": [
			"Network",
			"VPN"
		],
		"paths": {
			"system": [
				"/etc/wireguard/",
				"/etc/openvpn/",
				"/etc/vpnc/",
				"/etc/wpa_supplicant/",
				"/etc/tor/",
				"/etc/i2p/"
			],
			"user": [
				"~/.config/wireguard/",
				"~/.config/openvpn/"
			]
		}
	},
	{
		"order": "5.0",
		"title": "System Services / Logging",
		"keywords": [
			"System Services",
			"Logging"
		],
		"paths": {
			"system": [
				"/etc/rsyslog.conf",
				"/etc/rsyslog.d/"
			],
			"user": []
		}
	},
	{
		"order": "5.1",
		"title": "System Services / Time",
		"keywords": [
			"System Services",
			"Time"
		],
		"paths": {
			"system": [
				"/etc/chrony.conf",
				"/etc/systemd/timesyncd.conf"
			],
			"user": []
		}
	},
	{
		"order": "5.2",
		"title": "System Services / Locale",
		"keywords": [
			"System Services",
			"Locale"
		],
		"paths": {
			"system": [
				"/etc/locale.conf",
				"/etc/xdg/user-dirs.defaults"
			],
			"user": [
				"~/.config/locale.conf",
				"~/.config/user-dirs.dirs"
			]
		}
	},
	{
		"order": "5.3",
		"title": "System Services / Boot",
		"keywords": [
			"System Services",
			"Boot"
		],
		"paths": {
			"system": [
				"/etc/plymouth/"
			],
			"user": []
		}
	},
	{
		"order": "5.4",
		"title": "System Services / Login",
		"keywords": [
			"System Services",
			"Login"
		],
		"paths": {
			"system": [
				"/etc/login.defs"
			],
			"user": []
		}
	},
	{
		"order": "5.5",
		"title": "System Services / Issue",
		"keywords": [
			"System Services",
			"Issue"
		],
		"paths": {
			"system": [
				"/etc/issue",
				"/etc/issue.d/",
				"/etc/issue.net"
			],
			"user": []
		}
	},
	{
		"order": "5.6",
		"title": "System Services / Mail",
		"keywords": [
			"System Services",
			"Mail"
		],
		"paths": {
			"system": [
				"/etc/aliases"
			],
			"user": []
		}
	},
	{
		"order": "6.0",
		"title": "Shell / Login",
		"keywords": [
			"Shell",
			"Login"
		],
		"paths": {
			"system": [
				"/etc/profile",
				"/etc/profile.d/"
			],
			"user": [
				"~/.profile",
				"~/.bash_profile"
			]
		}
	},
	{
		"order": "6.1",
		"title": "Shell / Interactive",
		"keywords": [
			"Shell",
			"Interactive"
		],
		"paths": {
			"system": [
				"/etc/bash.bashrc",
				"/etc/fish/config.fish",
				"/etc/zsh/zshrc"
			],
			"user": [
				"~/.bashrc",
				"~/.config/fish/config.fish",
				"~/.zshrc"
			]
		}
	},
	{
		"order": "6.2",
		"title": "Shell / Completion",
		"keywords": [
			"Shell",
			"Completion"
		],
		"paths": {
			"system": [
				"/etc/bash_completion.d/"
			],
			"user": []
		}
	},
	{
		"order": "6.3",
		"title": "Shell / CSH",
		"keywords": [
			"Shell",
			"CSH"
		],
		"paths": {
			"system": [
				"/etc/csh.cshrc",
				"/etc/csh.login"
			],
			"user": []
		}
	},
	{
		"order": "7.0",
		"title": "Security / Authentication",
		"keywords": [
			"Security",
			"Authentication"
		],
		"paths": {
			"system": [
				"/etc/polkit-1/rules.d/",
				"/etc/pam.d/",
				"/etc/nsswitch.conf",
				"/etc/sssd/",
				"/etc/security/",
				"/etc/authselect/"
			],
			"user": []
		}
	},
	{
		"order": "7.1",
		"title": "Security / Encryption",
		"keywords": [
			"Security",
			"Encryption"
		],
		"paths": {
			"system": [
				"/etc/skel/.gnupg/",
				"/etc/ssl/",
				"/etc/gnupg/",
				"/etc/pki/",
				"/etc/crypto-policies/"
			],
			"user": [
				"~/.gnupg/"
			]
		}
	},
	{
		"order": "7.2",
		"title": "Security / SSH",
		"keywords": [
			"Security",
			"SSH"
		],
		"paths": {
			"system": [
				"/etc/ssh/ssh_config",
				"/etc/ssh/"
			],
			"user": [
				"~/.ssh/config"
			]
		}
	},
	{
		"order": "7.2",
		"title": "Security / SSH Daemon",
		"keywords": [
			"Security",
			"SSH Daemon"
		],
		"paths": {
			"system": [
				"/etc/ssh/sshd_config"
			],
			"user": []
		}
	},
	{
		"order": "7.3",
		"title": "Security / Firewall",
		"keywords": [
			"Security",
			"Firewall"
		],
		"paths": {
			"system": [
				"/etc/nftables.conf",
				"/etc/iptables/",
				"/etc/firewalld/",
				"/etc/nftables/"
			],
			"user": []
		}
	},
	{
		"order": "7.4",
		"title": "Security / SELinux",
		"keywords": [
			"Security",
			"SELinux"
		],
		"paths": {
			"system": [
				"/etc/selinux/",
				"/etc/sestatus.conf",
				"/etc/setroubleshoot/"
			],
			"user": []
		}
	},
	{
		"order": "7.5",
		"title": "Security / Antivirus",
		"keywords": [
			"Security",
			"Antivirus"
		],
		"paths": {
			"system": [
				"/etc/clamd.d/"
			],
			"user": []
		}
	},
	{
		"order": "7.6",
		"title": "Security / TPM",
		"keywords": [
			"Security",
			"TPM"
		],
		"paths": {
			"system": [
				"/etc/tpm2-tss/"
			],
			"user": []
		}
	},
	{
		"order": "7.7",
		"title": "Security / Kerberos",
